/*
 * MSPI_Config.h
 *
 *  Created on: Feb 26, 2022
 *      Author: Dell
 */

#ifndef MCAL_MSPI_MSPI_CONFIG_H_
#define MCAL_MSPI_MSPI_CONFIG_H_

/*MSPI_DATAORDER Option
 * 1-MSPI_LSB_DATAORDER
 * 2-MSPI_MSB_DATAORDER*/
#define MSPI_DATAORDER  MSPI_LSB_DATAORDER

/*Clock Polarity option
 * 1-MSPI_RISING_POLARITY
 * 2-MSPI_FALLING_POLARITY*/
#define MSPI_SETCLOCKPOLARIT  MSPI_RISING_POLARITY
/*Clock Phase option
 * 1-MSPI_SETUP_PHASE
 * 2-MSPI_SAMPLE_PHASE*/
#define MSPI_SETCLOCKPHASE   MSPI_SETUP_PHASE
/*Double Option
 * 1-MSPI_DOUBLESPEED
 * 2-MSPI_NO_DOUBLESPEED*/
#define MSPI_SETDOUBLESPEED  MSPI_NO_DOUBLESPEED

/*SPI PreScaler Option
 * 1-MSPI_PRESCALER_4_NODOUBLE
 * 2-MSPI_PRESCALER_16_NODOUBLE
 * 3-MSPI_PRESCALER_64_NODOUBLE
 * 4-MSPI_PRESCALER_128_NODOUBLE
 * 5-MSPI_PRESCALER_2_Double
 * 6-MSPI_PRESCALER_8_Double
 * -MSPI_PRESCALER_32_Double
 * 8-MSPI_PRESCALER_64_Double */
#define MSPI_PRESCALER   MSPI_PRESCALER_16_NODOUBLE

#endif /* MCAL_MSPI_MSPI_CONFIG_H_ */
